FROM public.ecr.aws/lambda/python:3.13

RUN pip install uv 

ENV UV_COMPILE_BYTECODE=1

ENV UV_NO_INSTALLER_METADATA=1

ENV UV_LINK_MODE=copy 

COPY ./pyproject.toml ./uv.lock ./ 

RUN uv export --frozen --no-emit-workspace --no-dev --no-editable -o requirements.txt && \
    uv pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY ./stream_processor.py  ./models.py ./settings.py ./

CMD ["stream_processor.lambda_handler"]