FROM public.ecr.aws/lambda/python:3.13

RUN pip install uv 

ENV UV_COMPILE_BYTECODE=1

ENV UV_NO_INSTALLER_METADATA=1

ENV UV_LINK_MODE=copy 

COPY ./pyproject.toml ./uv.lock ./ 

RUN uv export --frozen --no-emit-workspace --no-dev --no-editable -o requirements.txt && \
    uv pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY ./src/api.py  ./src/models.py ./src/settings.py ./src/shared.py ./src/

CMD ["src.api.lambda_handler"]